pipeline {
  agent any
    environment {
        PROJECT_ID = 'essential-smoke-274903'
        LOCATION = 'us-central1-c'
        CREDENTIALS_ID = 'gkeweb'
        CLUSTER_NAME = 'hirelab'
                  
    }
  stages {
    stage('Deploy Prometheus-grafana-alertmanager Monitoring on GKE Platform') {
       steps{  
	          sh 'kubectl apply -f monitoring/prometheus'
	          step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME, location: env.LOCATION, manifestPattern: 'monitoring/prometheus', credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])
		  step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME, location: env.LOCATION, manifestPattern: 'monitoring/alertmanager', credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])
 		  step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME, location: env.LOCATION, manifestPattern: 'monitoring/grafana', credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])
		  step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME, location: env.LOCATION, manifestPattern: 'monitoring/kube-state-metrics', credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])
		  step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME, location: env.LOCATION, manifestPattern: 'monitoring/node-exporter', credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])

       }
      }
  }
}



